from django.test import TestCase

# Create your tests here.
from django.urls import reverse
from django.contrib.auth import get_user_model
from .models import Book
from accounts.models import Librarian  # Assuming accounts app is installed

User = get_user_model()

class BookModelTest(TestCase):
    # Test the Book model
    def test_book_creation(self):
        book = Book.objects.create(
            book_id='B001',
            title='Test Book',
            author='Test Author',
            available_copies=5
        )
        self.assertEqual(str(book), 'Test Book - Test Author')
        self.assertEqual(book.available_copies, 5)

class BookViewTest(TestCase):
    def setUp(self):
        # Create a regular user
        self.user = User.objects.create_user(username='user', password='pass')
        # Create a librarian user (with associated Librarian profile)
        self.librarian_user = User.objects.create_user(username='lib', password='pass')
        Librarian.objects.create(user=self.librarian_user, employee_id='L001')
        # Create a book for testing
        self.book = Book.objects.create(
            book_id='B001',
            title='Book1',
            author='Author1',
            available_copies=3
        )

    # ---------- BookListView tests ----------
    def test_book_list_search(self):
        self.client.login(username='user', password='pass')
        response = self.client.get(reverse('book_list'), {'search': 'Book1'})
        self.assertContains(response, 'Book1')
        response = self.client.get(reverse('book_list'), {'search': 'Nonexistent'})
        self.assertNotContains(response, 'Book1')

    # ---------- BookCreateView tests ----------
    def test_book_create_creates_book(self):
        self.client.login(username='lib', password='pass')
        data = {
            'title': 'New Book',
            'author': 'New Author',
            'available_copies': 2,
            # book_id is not provided; it will be auto-generated by the view
        }
        response = self.client.post(reverse('book_create'), data)
        self.assertRedirects(response, reverse('book_list'))
        self.assertEqual(Book.objects.count(), 2)  # Original 1 + new 1
        new_book = Book.objects.get(title='New Book')
        self.assertIsNotNone(new_book.book_id)
        self.assertTrue(new_book.book_id)  # Non-empty

    # ---------- BookUpdateView tests ----------
    def test_book_update_updates_book(self):
        self.client.login(username='lib', password='pass')
        url = reverse('book_update', args=[self.book.pk])
        data = {
            'book_id': 'UPDATED',
            'title': 'Updated Title',
            'author': 'Updated Author',
            'available_copies': 5
        }
        response = self.client.post(url, data)
        self.assertRedirects(response, reverse('book_list'))
        self.book.refresh_from_db()
        self.assertEqual(self.book.title, 'Updated Title')
        self.assertEqual(self.book.author, 'Updated Author')
        self.assertEqual(self.book.available_copies, 5)
        self.assertEqual(self.book.book_id, 'UPDATED')

    # ---------- BookDeleteView tests ----------
    def test_book_delete_permission(self):
        url = reverse('book_delete', args=[self.book.pk])
        # Not logged in
        response = self.client.get(url)
        self.assertRedirects(response, f"{reverse('login')}?next={url}")
        # Regular user
        self.client.login(username='user', password='pass')
        response = self.client.get(url)
        self.assertEqual(response.status_code, 403)
        # Librarian
        self.client.login(username='lib', password='pass')
        response = self.client.get(url)
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'books/book_confirm_delete.html')

    def test_book_delete_deletes_book(self):
        self.client.login(username='lib', password='pass')
        url = reverse('book_delete', args=[self.book.pk])
        response = self.client.post(url)  # Delete view uses POST to perform deletion
        self.assertRedirects(response, reverse('book_list'))
        self.assertEqual(Book.objects.count(), 0)