# Generated by Django 5.2.12 on 2026-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Book ID'),
        ),
    ]