# Generated by Django 5.2.12 on 2026-03-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=50, unique=True, verbose_name='借阅编号')),
                ('student_username', models.CharField(max_length=150, verbose_name='学生用户名')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('book_id', models.CharField(max_length=50, verbose_name='图书编号')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='借阅日期')),
                ('due_date', models.DateField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还日期')),
                ('status', models.CharField(choices=[('borrowing', '借阅中'), ('returned', '已归还')], default='borrowing', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
            },
        ),
    ]
