# Generated by Django 5.2.12 on 2026-03-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=50, unique=True, verbose_name='Loan ID')),
                ('student_username', models.CharField(max_length=150, verbose_name='Student Username')),
                ('student_id', models.CharField(max_length=20, verbose_name='Student ID')),
                ('book_id', models.CharField(max_length=50, verbose_name='Book ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='Book Title')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Loan Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Return Date')),
                ('status', models.CharField(choices=[('borrowing', 'Borrowing'), ('returned', 'Returned')], default='borrowing', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Loan Record',
                'verbose_name_plural': 'Loan Records',
            },
        ),
    ]
    