# Generated by Django 5.2.12 on 2026-03-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrecord',
            options={'ordering': ['-loan_date'], 'verbose_name': '借阅记录', 'verbose_name_plural': '借阅记录'},
        ),
        migrations.RemoveField(
            model_name='loanrecord',
            name='return_date',
        ),
    ]
